/* ── Job data – single source of truth for all listings across the portal.
   Each job carries categories (used by chips + category select), a location
   type, a seniority level and a position type — the latter three are rendered
   as colored pill badges.  Salary is expressed in whole-thousands (annual, USD). */

var JOBS = [
  {
    title: 'UX Designer',
    company: 'Google Drive',
    icon: 'fab fa-google-drive',
    categories: ['design'],
    salaryMin: 80,
    salaryMax: 120,
    postedDays: 1,
    type: 'Full-time',
    location: 'Remote',
    level: 'Junior',
    dashboard: true
  },
  {
    title: 'JavaScript Developer',
    company: 'Google',
    icon: 'fab fa-google',
    categories: ['programming', 'javascript'],
    salaryMin: 135,
    salaryMax: 165,
    postedDays: 2,
    type: 'Full-time',
    location: 'Hybrid',
    level: 'Senior',
    dashboard: true
  },
  {
    title: 'Product Developer',
    company: 'Facebook',
    icon: 'fab fa-facebook',
    categories: ['programming'],
    salaryMin: 140,
    salaryMax: 180,
    postedDays: 2,
    type: 'Full-time',
    location: 'On-site',
    level: 'Manager',
    dashboard: true
  },
  {
    title: 'Programmer',
    company: 'GitHub',
    icon: 'fab fa-git-alt',
    categories: ['programming', 'php'],
    salaryMin: 80,
    salaryMax: 110,
    postedDays: 3,
    type: 'Full-time',
    location: 'Remote',
    level: 'Junior',
    dashboard: true
  },
  {
    title: 'React.js Expert',
    company: 'YouTube',
    icon: 'fab fa-youtube',
    categories: ['programming', 'javascript'],
    salaryMin: 150,
    salaryMax: 190,
    postedDays: 4,
    type: 'Full-time',
    location: 'Remote',
    level: 'Senior',
    dashboard: true
  },
  {
    title: 'WordPress Developer',
    company: 'WordPress',
    icon: 'fab fa-wordpress',
    categories: ['php'],
    salaryMin: 60,
    salaryMax: 90,
    postedDays: 5,
    type: 'Full-time',
    location: 'Remote',
    level: 'Mid',
    dashboard: true
  },
  {
    title: 'Angular Developer',
    company: 'Angular',
    icon: 'fab fa-angular',
    categories: ['programming', 'javascript'],
    salaryMin: 120,
    salaryMax: 160,
    postedDays: 3,
    type: 'Full-time',
    location: 'Hybrid',
    level: 'Senior',
    dashboard: true
  },
  {
    title: 'UI Designer',
    company: 'Figma',
    icon: 'fab fa-figma',
    categories: ['design'],
    salaryMin: 70,
    salaryMax: 95,
    postedDays: 2,
    type: 'Full-time',
    location: 'Remote',
    level: 'Junior',
    dashboard: true
  },
  {
    title: 'Backend Engineer',
    company: 'Microsoft',
    icon: 'fab fa-microsoft',
    categories: ['programming'],
    salaryMin: 130,
    salaryMax: 170,
    postedDays: 5,
    type: 'Full-time',
    location: 'Hybrid',
    level: 'Senior',
    dashboard: false
  },
  {
    title: 'Data Analyst',
    company: 'Amazon',
    icon: 'fab fa-amazon',
    categories: ['marketing'],
    salaryMin: 85,
    salaryMax: 120,
    postedDays: 6,
    type: 'Contract',
    location: 'Remote',
    level: 'Mid',
    dashboard: false
  },
  {
    title: 'Product Designer',
    company: 'Apple',
    icon: 'fab fa-apple',
    categories: ['design'],
    salaryMin: 100,
    salaryMax: 140,
    postedDays: 2,
    type: 'Full-time',
    location: 'Hybrid',
    level: 'Mid',
    dashboard: false
  },
  {
    title: 'Frontend Developer',
    company: 'Shopify',
    icon: 'fab fa-shopify',
    categories: ['programming', 'design'],
    salaryMin: 85,
    salaryMax: 120,
    postedDays: 3,
    type: 'Full-time',
    location: 'Remote',
    level: 'Junior',
    dashboard: false
  },
  {
    title: 'Growth Marketer',
    company: 'Airbnb',
    icon: 'fab fa-airbnb',
    categories: ['marketing'],
    salaryMin: 110,
    salaryMax: 150,
    postedDays: 4,
    type: 'Full-time',
    location: 'On-site',
    level: 'Manager',
    dashboard: false
  },
  {
    title: 'Cloud Engineer',
    company: 'Dropbox',
    icon: 'fab fa-dropbox',
    categories: ['programming'],
    salaryMin: 140,
    salaryMax: 180,
    postedDays: 5,
    type: 'Full-time',
    location: 'Remote',
    level: 'Senior',
    dashboard: false
  },
  {
    title: 'SEO Specialist',
    company: 'LinkedIn',
    icon: 'fab fa-linkedin-in',
    categories: ['marketing'],
    salaryMin: 70,
    salaryMax: 100,
    postedDays: 3,
    type: 'Contract',
    location: 'Remote',
    level: 'Mid',
    dashboard: false
  },
  {
    title: 'Node.js Developer',
    company: 'Slack',
    icon: 'fab fa-slack',
    categories: ['programming'],
    salaryMin: 110,
    salaryMax: 150,
    postedDays: 2,
    type: 'Full-time',
    location: 'Remote',
    level: 'Mid',
    dashboard: false
  },
  {
    title: 'Brand Designer',
    company: 'Spotify',
    icon: 'fab fa-spotify',
    categories: ['design', 'marketing'],
    salaryMin: 75,
    salaryMax: 105,
    postedDays: 5,
    type: 'Full-time',
    location: 'Hybrid',
    level: 'Junior',
    dashboard: false
  },
  {
    title: 'DevOps Engineer',
    company: 'GitHub',
    icon: 'fab fa-git-alt',
    categories: ['programming'],
    salaryMin: 150,
    salaryMax: 190,
    postedDays: 6,
    type: 'Full-time',
    location: 'Remote',
    level: 'Senior',
    dashboard: false
  }
];